/*
 * El Sistema de Inventario de Bienes (SIB) fue desarrollado con la finalidad de
 * aportar una mejora al Centro de Educación Continua Unidad Morelia en cuanto
 * a la administración de los bienes muebles y equipo con los que cuenta.
 * 
 * Este software fue concebido, diseñado y desarrollado por el alumno cuyo seudónimo
 * adoptado es "Emoticón", como proyecto encomendado por el cumplimiento del servicio social.
 *
 */
package Login.RDU;


import Login.Login;
import javax.swing.JOptionPane;
import Login.RDU.DB.Aconexion;


/**
 *
 * @author Emoticon
 * @version 1.0.0.0_2
 */
public class NvoUsuario extends javax.swing.JFrame {

    /**
     * Creates new form NvoUsuario
     */
    public NvoUsuario() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Registrar cuenta de usuario");
        
        campoContra.setEditable(false);
        campoContra2.setEditable(false);
        botonVcontraseñas.setVisible(false);
        
        campoPregunta1.setEnabled(false);
        campoPregunta2.setEnabled(false);
        campoPregunta3.setEnabled(false);
        campoPregunta4.setEnabled(false);
        campoRespuesta1.setEnabled(false);
        campoRespuesta2.setEnabled(false);
        campoRespuesta3.setEnabled(false);
        campoRespuesta4.setEnabled(false);
        botonGuardar.setVisible(false);
        
        botonModDU.setVisible(false);
         
    }
    
    private String nomUsuario;
    private String contra;
    private String contra2;
    
    private String pregunta1;
    private String pregunta2;
    private String pregunta3;
    private String pregunta4;
    
    private String respuesta1;
    private String respuesta2;
    private String respuesta3;
    private String respuesta4;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        etiquetaUsuario = new javax.swing.JLabel();
        etiquetaContra = new javax.swing.JLabel();
        campoUsuario = new javax.swing.JTextField();
        etiquetaContra2 = new javax.swing.JLabel();
        campoContra = new javax.swing.JPasswordField();
        campoContra2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        botonVcontraseñas = new javax.swing.JButton();
        botonModDU = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        etiquetaPregunta1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        campoPregunta2 = new javax.swing.JTextField();
        campoPregunta1 = new javax.swing.JTextField();
        campoPregunta3 = new javax.swing.JTextField();
        campoRespuesta1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campoRespuesta3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        campoRespuesta2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        campoPregunta4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        campoRespuesta4 = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setText("SIB v1.0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Registrar nuevo usuario");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        etiquetaUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        etiquetaUsuario.setText("Nombre de usuario:");

        etiquetaContra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        etiquetaContra.setText("Contraseña:");

        campoUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoUsuario.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoUsuarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoUsuarioKeyTyped(evt);
            }
        });

        etiquetaContra2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        etiquetaContra2.setText("Repita la contraseña:");

        campoContra.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoContra.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoContraMouseClicked(evt);
            }
        });
        campoContra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoContraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoContraKeyTyped(evt);
            }
        });

        campoContra2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoContra2.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoContra2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoContra2MouseClicked(evt);
            }
        });
        campoContra2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoContra2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoContra2KeyTyped(evt);
            }
        });

        jLabel3.setText("Datos de usuario:");

        botonVcontraseñas.setBackground(new java.awt.Color(51, 0, 0));
        botonVcontraseñas.setForeground(new java.awt.Color(255, 255, 255));
        botonVcontraseñas.setText("Verificar");
        botonVcontraseñas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonVcontraseñas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVcontraseñasActionPerformed(evt);
            }
        });

        botonModDU.setBackground(new java.awt.Color(51, 0, 0));
        botonModDU.setForeground(new java.awt.Color(255, 255, 255));
        botonModDU.setText("Modificar datos de usuario");
        botonModDU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonModDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModDUActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(232, 232, 232)
                        .addComponent(botonModDU, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(etiquetaContra)
                                        .addComponent(etiquetaUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(177, 177, 177))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(campoContra)
                                    .addGap(108, 108, 108)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(etiquetaContra2)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(campoContra2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(botonVcontraseñas))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonModDU, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaContra2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaContra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoContra2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVcontraseñas))
                .addGap(0, 28, Short.MAX_VALUE))
        );

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel7.setText("Datos de recuperación de cuenta:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Preguntas y respuestas secretas");

        etiquetaPregunta1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        etiquetaPregunta1.setText("Pregunta 1:");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Respuesta:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("Respuesta:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Pregunta 2:");

        campoPregunta2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoPregunta2.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoPregunta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPregunta2ActionPerformed(evt);
            }
        });
        campoPregunta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPregunta2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPregunta2KeyTyped(evt);
            }
        });

        campoPregunta1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoPregunta1.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoPregunta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPregunta1ActionPerformed(evt);
            }
        });
        campoPregunta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPregunta1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPregunta1KeyTyped(evt);
            }
        });

        campoPregunta3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoPregunta3.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoPregunta3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPregunta3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPregunta3KeyTyped(evt);
            }
        });

        campoRespuesta1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoRespuesta1.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoRespuesta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoRespuesta1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRespuesta1KeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Pregunta 3:");

        campoRespuesta3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoRespuesta3.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoRespuesta3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoRespuesta3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRespuesta3KeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Respuesta:");

        campoRespuesta2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoRespuesta2.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoRespuesta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoRespuesta2ActionPerformed(evt);
            }
        });
        campoRespuesta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoRespuesta2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRespuesta2KeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("Pregunta 4:");

        campoPregunta4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoPregunta4.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoPregunta4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoPregunta4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPregunta4KeyTyped(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("Respuesta:");

        campoRespuesta4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        campoRespuesta4.setSelectionColor(new java.awt.Color(51, 0, 0));
        campoRespuesta4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoRespuesta4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoRespuesta4KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGap(412, 412, 412)
                                .addComponent(jLabel8))
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiquetaPregunta1)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoPregunta1)
                                    .addComponent(campoPregunta2, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE))
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel11))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel14))))
                            .addGroup(panel2Layout.createSequentialGroup()
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoPregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel2Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(campoPregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(campoRespuesta3)
                            .addComponent(campoRespuesta1)
                            .addComponent(campoRespuesta2)
                            .addComponent(campoRespuesta4, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE))))
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(26, 26, 26)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaPregunta1)
                    .addComponent(jLabel11)
                    .addComponent(campoPregunta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoPregunta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(campoRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(campoPregunta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(campoRespuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(campoPregunta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(campoRespuesta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        botonGuardar.setBackground(new java.awt.Color(51, 0, 0));
        botonGuardar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        botonGuardar.setForeground(new java.awt.Color(255, 255, 255));
        botonGuardar.setText("Guardar");
        botonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonGuardarMouseEntered(evt);
            }
        });
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        botonGuardar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                botonGuardarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(348, 348, 348)
                .addComponent(jLabel2))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 1019, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(201, 201, 201))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPregunta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPregunta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPregunta1ActionPerformed

    private void campoPregunta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPregunta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPregunta2ActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        int conf = JOptionPane.showConfirmDialog(rootPane, "Sus respuestas deben ser exactas, cada letra, signo, número, espacio, minúscula o minúscula\n" + 
                "será verificada cuando se le soliciten al modificar o recuperar su contraseña",
                "Verifique que todos sus datos sean correctos",JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE);
        
        // El usuario da la confirmación de que sí desea guardar los datos como están
        if(conf == 0){
            nomUsuario = campoUsuario.getText();
            contra = campoContra.getText();
            pregunta1 = campoPregunta1.getText();
            pregunta2 = campoPregunta2.getText();
            pregunta3 = campoPregunta3.getText();
            pregunta4 = campoPregunta4.getText();
            respuesta1 = campoRespuesta1.getText();
            respuesta2 = campoRespuesta2.getText();
            respuesta3 = campoRespuesta3.getText();
            respuesta4 = campoRespuesta4.getText();
            
                Aconexion cn = new Aconexion();
                boolean verificadorR = cn.RegistrarUsuario(nomUsuario, contra, pregunta1,
                        pregunta2, pregunta3, pregunta4, respuesta1, respuesta2, respuesta3, respuesta4);
                
                    if(verificadorR != false){
                        Login l = new Login();
                        l.setVisible(true);
                        dispose();
                        JOptionPane.showMessageDialog(rootPane, "El usuario: '" + nomUsuario + "', se ha registrado exitosamente en el sistema\n" +
                                "¡Ahora puede iniciar sesión!",
                                "¡Éxito!", WIDTH);
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "El usuario no se ha podido registrar por causas desconocodas, si persiste el problema contacte al desarrolador de la aplicación",
                                "¡Éxito!", JOptionPane.ERROR_MESSAGE);
                    }
        }
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void campoUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuarioKeyReleased
        if (evt.getSource() == campoUsuario) {
                nomUsuario = campoUsuario.getText();
                if (!nomUsuario.isEmpty()) {
                        campoContra.setEditable(true);
                } else{
                        campoContra.setEditable(false);
                        campoContra.setText("");
                }
            }
    }//GEN-LAST:event_campoUsuarioKeyReleased

    private void campoContraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoContraKeyReleased
        if (evt.getSource() == campoContra) {
                nomUsuario = campoUsuario.getText();
                contra = campoContra.getText();
                if (!contra.isEmpty() & !nomUsuario.isEmpty()) {
                        campoContra2.setEditable(true);
                } else if(!nomUsuario.isEmpty() & contra.isEmpty()){
                        campoContra2.setEditable(false);
                        campoContra2.setText("");
                        campoContra.setText("");
                        
        campoPregunta1.setEnabled(false);
        campoPregunta2.setEnabled(false);
        campoPregunta3.setEnabled(false);
        campoPregunta4.setEnabled(false);
        campoRespuesta1.setEnabled(false);
        campoRespuesta2.setEnabled(false);
        campoRespuesta3.setEnabled(false);
        campoRespuesta4.setEnabled(false);
        botonGuardar.setVisible(false);
                } 
            }
        
    }//GEN-LAST:event_campoContraKeyReleased

    private void campoContra2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoContra2KeyReleased
        if (evt.getSource() == campoContra2) {
                nomUsuario = campoUsuario.getText();
                contra2 = campoContra2.getText();
                if (!contra.isEmpty() & !nomUsuario.isEmpty() & !contra2.isEmpty()) {
                        botonVcontraseñas.setVisible(true);
                } else{
        campoPregunta1.setEnabled(false);
        campoPregunta2.setEnabled(false);
        campoPregunta3.setEnabled(false);
        campoPregunta4.setEnabled(false);
        campoRespuesta1.setEnabled(false);
        campoRespuesta2.setEnabled(false);
        campoRespuesta3.setEnabled(false);
        campoRespuesta4.setEnabled(false);
        botonGuardar.setVisible(false);
                        campoContra2.setText("");
                        campoContra.setText("");
                        JOptionPane.showMessageDialog(rootPane, "Debe asignar un nombre de usuario y contraseña", "Mensaje", 
                                JOptionPane.OK_OPTION);
                }
            }
    }//GEN-LAST:event_campoContra2KeyReleased

    private void campoContraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoContraMouseClicked
       nomUsuario = campoUsuario.getText();
            if(nomUsuario.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Primero asigne un nombre de usuario", "Mensaje", JOptionPane.OK_OPTION);
            }
            
    }//GEN-LAST:event_campoContraMouseClicked

    private void campoContra2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoContra2MouseClicked
            nomUsuario = campoUsuario.getText();
            contra = campoContra.getText();
            if(nomUsuario.isEmpty() && contra.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Debe introducir un nombre de usuario y contraseña", "Mensaje", JOptionPane.OK_OPTION);
        campoPregunta1.setEnabled(false);
        campoPregunta2.setEnabled(false);
        campoPregunta3.setEnabled(false);
        campoPregunta4.setEnabled(false);
        campoRespuesta1.setEnabled(false);
        campoRespuesta2.setEnabled(false);
        campoRespuesta3.setEnabled(false);
        campoRespuesta4.setEnabled(false);
        botonGuardar.setVisible(false);
            }
              else if(nomUsuario.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Primero asigne un nombre de usuario", "Mensaje", JOptionPane.OK_OPTION);
        campoPregunta1.setEnabled(false);
        campoPregunta2.setEnabled(false);
        campoPregunta3.setEnabled(false);
        campoPregunta4.setEnabled(false);
        campoRespuesta1.setEnabled(false);
        campoRespuesta2.setEnabled(false);
        campoRespuesta3.setEnabled(false);
        campoRespuesta4.setEnabled(false);
        botonGuardar.setVisible(false);
            } else if(contra.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Primero introduzca una contraseña", "Mensaje", JOptionPane.OK_OPTION);
        campoPregunta1.setEnabled(false);
        campoPregunta2.setEnabled(false);
        campoPregunta3.setEnabled(false);
        campoPregunta4.setEnabled(false);
        campoRespuesta1.setEnabled(false);
        campoRespuesta2.setEnabled(false);
        campoRespuesta3.setEnabled(false);
        campoRespuesta4.setEnabled(false);
        botonGuardar.setVisible(false);
            }
            
    }//GEN-LAST:event_campoContra2MouseClicked

    private void botonVcontraseñasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVcontraseñasActionPerformed
                            contra = campoContra.getText();
                            contra2 = campoContra2.getText();
                                if(!contra2.equals(contra)){
                                    JOptionPane.showMessageDialog(rootPane, 
                                            "Las contraseñas no coinciden, verifiquelas y vuelva a intentar", "Mensaje", JOptionPane.ERROR_MESSAGE);
                                    campoContra.setText("");
                                    campoContra2.setText("");
                                } else{
                                    campoUsuario.setEnabled(false);
                                    campoContra.setEnabled(false);
                                    campoContra2.setEnabled(false);
                                            pregunta1 = campoPregunta1.getText();
                                            pregunta2 = campoPregunta2.getText();
                                            pregunta3 = campoPregunta3.getText();
                                            pregunta4 = campoPregunta4.getText();
                                            respuesta1 = campoRespuesta1.getText();
                                            respuesta2 = campoRespuesta2.getText();
                                            respuesta3 = campoRespuesta3.getText();
                                            respuesta4 = campoRespuesta4.getText();
                                            
                                            // Activación de campos de preguntas
                                            campoPregunta1.setEnabled(true);
                                        if(respuesta1.isEmpty()){
                                            if(pregunta2.isEmpty()){
                                                campoPregunta2.setEnabled(false);
                                            }else{
                                                campoPregunta2.setEnabled(true);
                                            }
                                        } else{
                                            campoPregunta2.setEnabled(true);
                                        }
                                        if(respuesta2.isEmpty()){
                                            if(pregunta3.isEmpty()){
                                                campoPregunta3.setEnabled(false);
                                            }else{
                                                campoPregunta3.setEnabled(true);
                                            }
                                        } else{
                                            campoPregunta3.setEnabled(true);
                                        }
                                        if(respuesta3.isEmpty()){
                                            if(pregunta4.isEmpty()){
                                                campoPregunta4.setEnabled(false);
                                            }else{
                                                campoPregunta4.setEnabled(true);
                                            }
                                        } else{
                                            campoPregunta4.setEnabled(true);
                                        }
                                            // Activación de campos de respuestas
                                        if(pregunta1.isEmpty()){
                                            campoRespuesta1.setEnabled(false);
                                        } else{
                                                    campoRespuesta1.setEnabled(true);
                                        }
                                        if(pregunta2.isEmpty()){
                                            campoRespuesta2.setEnabled(false);
                                        } else{
                                                    campoRespuesta2.setEnabled(true);
                                        }
                                        if(pregunta3.isEmpty()){
                                            campoRespuesta3.setEnabled(false);
                                        } else{
                                                    campoRespuesta3.setEnabled(true);
                                        }
                                        if(pregunta4.isEmpty()){
                                            campoRespuesta4.setEnabled(false);
                                        } else{
                                                    campoRespuesta4.setEnabled(true);
                                        }
                                        
                                            botonGuardar.setVisible(true);
                                            if(!pregunta1.isEmpty() & !pregunta2.isEmpty() & !pregunta3.isEmpty() & !pregunta4.isEmpty() & 
                                                    !respuesta1.isEmpty() & !respuesta2.isEmpty() & !respuesta3.isEmpty() & !respuesta4.isEmpty()){
                                                                    botonGuardar.setEnabled(true);    
                                            }else{
                                                botonGuardar.setEnabled(false);
                                            }
                                            botonModDU.setVisible(true);
                                           
                                            botonVcontraseñas.setEnabled(true);
                                            botonVcontraseñas.setVisible(false);
                                    JOptionPane.showMessageDialog(rootPane, 
                                            "¡Las contraseñas coinciden correctamente!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                                }
    }//GEN-LAST:event_botonVcontraseñasActionPerformed

    private void botonModDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModDUActionPerformed
            campoUsuario.setEnabled(true);
            campoContra.setEnabled(true);
            campoContra2.setEnabled(true);
            campoContra.setText("");
            campoContra2.setText("");
                campoPregunta1.setEnabled(false);
                campoPregunta2.setEnabled(false);
                campoPregunta3.setEnabled(false);
                campoPregunta4.setEnabled(false);
                campoRespuesta1.setEnabled(false);
                campoRespuesta2.setEnabled(false);
                campoRespuesta3.setEnabled(false);
                campoRespuesta4.setEnabled(false);
                botonGuardar.setVisible(false);
                
                botonModDU.setVisible(false);
    }//GEN-LAST:event_botonModDUActionPerformed

    private void campoPregunta1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPregunta1KeyReleased
        if (evt.getSource() == campoPregunta1) {
                pregunta1 = campoPregunta1.getText();
                if (!pregunta1.isEmpty()) {
                        campoRespuesta1.setEnabled(true);
                } else{
                        campoRespuesta1.setEnabled(false);
                }
            }                                        
                                            pregunta1 = campoPregunta1.getText();
                                            pregunta2 = campoPregunta2.getText();
                                            pregunta3 = campoPregunta3.getText();
                                            pregunta4 = campoPregunta4.getText();
                                            respuesta1 = campoRespuesta1.getText();
                                            respuesta2 = campoRespuesta2.getText();
                                            respuesta3 = campoRespuesta3.getText();
                                            respuesta4 = campoRespuesta4.getText();
                if (!pregunta1.isEmpty() & !pregunta2.isEmpty() & !pregunta3.isEmpty() & !pregunta4.isEmpty() & 
                        !respuesta1.isEmpty() & !respuesta2.isEmpty() & !respuesta3.isEmpty() & !respuesta4.isEmpty()) {
                        botonGuardar.setEnabled(true);
                } else{
                        botonGuardar.setEnabled(false);
                }
    }//GEN-LAST:event_campoPregunta1KeyReleased

    private void campoRespuesta1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRespuesta1KeyReleased
        if (evt.getSource() == campoRespuesta1) {
                respuesta1 = campoRespuesta1.getText();
                if (!respuesta1.isEmpty()) {
                        campoPregunta2.setEnabled(true);
                } else{
                        campoPregunta2.setEnabled(false);
                }
            }                                        
                                            pregunta1 = campoPregunta1.getText();
                                            pregunta2 = campoPregunta2.getText();
                                            pregunta3 = campoPregunta3.getText();
                                            pregunta4 = campoPregunta4.getText();
                                            respuesta1 = campoRespuesta1.getText();
                                            respuesta2 = campoRespuesta2.getText();
                                            respuesta3 = campoRespuesta3.getText();
                                            respuesta4 = campoRespuesta4.getText();
                if (!pregunta1.isEmpty() & !pregunta2.isEmpty() & !pregunta3.isEmpty() & !pregunta4.isEmpty() & 
                        !respuesta1.isEmpty() & !respuesta2.isEmpty() & !respuesta3.isEmpty() & !respuesta4.isEmpty()) {
                        botonGuardar.setEnabled(true);
                } else{
                        botonGuardar.setEnabled(false);
                }
    }//GEN-LAST:event_campoRespuesta1KeyReleased

    private void campoRespuesta2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRespuesta2KeyReleased
        if (evt.getSource() == campoRespuesta2) {
                respuesta2 = campoRespuesta2.getText();
                if (!respuesta2.isEmpty()) {
                        campoPregunta3.setEnabled(true);
                } else{
                        campoPregunta3.setEnabled(false);
                }
            }                                        
                                            pregunta1 = campoPregunta1.getText();
                                            pregunta2 = campoPregunta2.getText();
                                            pregunta3 = campoPregunta3.getText();
                                            pregunta4 = campoPregunta4.getText();
                                            respuesta1 = campoRespuesta1.getText();
                                            respuesta2 = campoRespuesta2.getText();
                                            respuesta3 = campoRespuesta3.getText();
                                            respuesta4 = campoRespuesta4.getText();
                if (!pregunta1.isEmpty() & !pregunta2.isEmpty() & !pregunta3.isEmpty() & !pregunta4.isEmpty() & 
                        !respuesta1.isEmpty() & !respuesta2.isEmpty() & !respuesta3.isEmpty() & !respuesta4.isEmpty()) {
                        botonGuardar.setEnabled(true);
                } else{
                        botonGuardar.setEnabled(false);
                }
    }//GEN-LAST:event_campoRespuesta2KeyReleased

    private void campoPregunta2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPregunta2KeyReleased
        if (evt.getSource() == campoPregunta2) {
                pregunta2 = campoPregunta2.getText();
                if (!pregunta2.isEmpty()) {
                        campoRespuesta2.setEnabled(true);
                } else{
                        campoRespuesta2.setEnabled(false);
                }
            }                                        
                                            pregunta1 = campoPregunta1.getText();
                                            pregunta2 = campoPregunta2.getText();
                                            pregunta3 = campoPregunta3.getText();
                                            pregunta4 = campoPregunta4.getText();
                                            respuesta1 = campoRespuesta1.getText();
                                            respuesta2 = campoRespuesta2.getText();
                                            respuesta3 = campoRespuesta3.getText();
                                            respuesta4 = campoRespuesta4.getText();
                if (!pregunta1.isEmpty() & !pregunta2.isEmpty() & !pregunta3.isEmpty() & !pregunta4.isEmpty() & 
                        !respuesta1.isEmpty() & !respuesta2.isEmpty() & !respuesta3.isEmpty() & !respuesta4.isEmpty()) {
                        botonGuardar.setEnabled(true);
                } else{
                        botonGuardar.setEnabled(false);
                }
    }//GEN-LAST:event_campoPregunta2KeyReleased

    private void campoPregunta3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPregunta3KeyReleased
        if (evt.getSource() == campoPregunta3) {
                pregunta3 = campoPregunta3.getText();
                if (!pregunta3.isEmpty()) {
                        campoRespuesta3.setEnabled(true);
                } else{
                        campoRespuesta3.setEnabled(false);
                }
            }                                        
                                            pregunta1 = campoPregunta1.getText();
                                            pregunta2 = campoPregunta2.getText();
                                            pregunta3 = campoPregunta3.getText();
                                            pregunta4 = campoPregunta4.getText();
                                            respuesta1 = campoRespuesta1.getText();
                                            respuesta2 = campoRespuesta2.getText();
                                            respuesta3 = campoRespuesta3.getText();
                                            respuesta4 = campoRespuesta4.getText();
                if (!pregunta1.isEmpty() & !pregunta2.isEmpty() & !pregunta3.isEmpty() & !pregunta4.isEmpty() & 
                        !respuesta1.isEmpty() & !respuesta2.isEmpty() & !respuesta3.isEmpty() & !respuesta4.isEmpty()) {
                        botonGuardar.setEnabled(true);
                } else{
                        botonGuardar.setEnabled(false);
                }
    }//GEN-LAST:event_campoPregunta3KeyReleased

    private void campoRespuesta3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRespuesta3KeyReleased
        if (evt.getSource() == campoRespuesta3) {
                respuesta3 = campoRespuesta2.getText();
                if (!respuesta3.isEmpty()) {
                        campoPregunta4.setEnabled(true);
                } else{
                        campoPregunta4.setEnabled(false);
                }
            }                                        
                                            pregunta1 = campoPregunta1.getText();
                                            pregunta2 = campoPregunta2.getText();
                                            pregunta3 = campoPregunta3.getText();
                                            pregunta4 = campoPregunta4.getText();
                                            respuesta1 = campoRespuesta1.getText();
                                            respuesta2 = campoRespuesta2.getText();
                                            respuesta3 = campoRespuesta3.getText();
                                            respuesta4 = campoRespuesta4.getText();
                if (!pregunta1.isEmpty() & !pregunta2.isEmpty() & !pregunta3.isEmpty() & !pregunta4.isEmpty() & 
                        !respuesta1.isEmpty() & !respuesta2.isEmpty() & !respuesta3.isEmpty() & !respuesta4.isEmpty()) {
                        botonGuardar.setEnabled(true);
                } else{
                        botonGuardar.setEnabled(false);
                }
    }//GEN-LAST:event_campoRespuesta3KeyReleased

    private void campoPregunta4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPregunta4KeyReleased
        if (evt.getSource() == campoPregunta4) {
                pregunta4 = campoPregunta4.getText();
                if (!pregunta4.isEmpty()) {
                        campoRespuesta4.setEnabled(true);
                } else{
                        campoRespuesta4.setEnabled(false);
                }
            }                                        
                                            pregunta1 = campoPregunta1.getText();
                                            pregunta2 = campoPregunta2.getText();
                                            pregunta3 = campoPregunta3.getText();
                                            pregunta4 = campoPregunta4.getText();
                                            respuesta1 = campoRespuesta1.getText();
                                            respuesta2 = campoRespuesta2.getText();
                                            respuesta3 = campoRespuesta3.getText();
                                            respuesta4 = campoRespuesta4.getText();
                if (!pregunta1.isEmpty() & !pregunta2.isEmpty() & !pregunta3.isEmpty() & !pregunta4.isEmpty() & 
                        !respuesta1.isEmpty() & !respuesta2.isEmpty() & !respuesta3.isEmpty() & !respuesta4.isEmpty()) {
                        botonGuardar.setEnabled(true);
                } else{
                        botonGuardar.setEnabled(false);
                }
    }//GEN-LAST:event_campoPregunta4KeyReleased

    private void campoRespuesta4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRespuesta4KeyReleased
        if (evt.getSource() == campoRespuesta4) {
                respuesta4 = campoRespuesta4.getText();
                if (!respuesta4.isEmpty()) {
                        botonGuardar.setVisible(true);
                } else{
                        botonGuardar.setEnabled(false);
                }
            }                                        
                                            pregunta1 = campoPregunta1.getText();
                                            pregunta2 = campoPregunta2.getText();
                                            pregunta3 = campoPregunta3.getText();
                                            pregunta4 = campoPregunta4.getText();
                                            respuesta1 = campoRespuesta1.getText();
                                            respuesta2 = campoRespuesta2.getText();
                                            respuesta3 = campoRespuesta3.getText();
                                            respuesta4 = campoRespuesta4.getText();
                if (!pregunta1.isEmpty() & !pregunta2.isEmpty() & !pregunta3.isEmpty() & !pregunta4.isEmpty() & 
                        !respuesta1.isEmpty() & !respuesta2.isEmpty() & !respuesta3.isEmpty() & !respuesta4.isEmpty()) {
                        botonGuardar.setEnabled(true);
                } else{
                        botonGuardar.setEnabled(false);
                }
    }//GEN-LAST:event_campoRespuesta4KeyReleased

    private void botonGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseEntered
                
    }//GEN-LAST:event_botonGuardarMouseEntered

    private void botonGuardarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_botonGuardarKeyReleased
        
    }//GEN-LAST:event_botonGuardarKeyReleased

    private void campoUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoUsuarioKeyTyped
        
    }//GEN-LAST:event_campoUsuarioKeyTyped

    private void campoContraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoContraKeyTyped
        
    }//GEN-LAST:event_campoContraKeyTyped

    private void campoContra2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoContra2KeyTyped
        
    }//GEN-LAST:event_campoContra2KeyTyped

    private void campoPregunta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPregunta1KeyTyped
        
    }//GEN-LAST:event_campoPregunta1KeyTyped

    private void campoRespuesta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRespuesta1KeyTyped
        
    }//GEN-LAST:event_campoRespuesta1KeyTyped

    private void campoPregunta2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPregunta2KeyTyped
        
    }//GEN-LAST:event_campoPregunta2KeyTyped

    private void campoRespuesta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoRespuesta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoRespuesta2ActionPerformed

    private void campoRespuesta2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRespuesta2KeyTyped
       
    }//GEN-LAST:event_campoRespuesta2KeyTyped

    private void campoPregunta3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPregunta3KeyTyped
        
    }//GEN-LAST:event_campoPregunta3KeyTyped

    private void campoRespuesta3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRespuesta3KeyTyped
        
    }//GEN-LAST:event_campoRespuesta3KeyTyped

    private void campoPregunta4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPregunta4KeyTyped
        
    }//GEN-LAST:event_campoPregunta4KeyTyped

    private void campoRespuesta4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoRespuesta4KeyTyped
        
    }//GEN-LAST:event_campoRespuesta4KeyTyped

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
                                                    pregunta1 = campoPregunta1.getText();
                                            pregunta2 = campoPregunta2.getText();
                                            pregunta3 = campoPregunta3.getText();
                                            pregunta4 = campoPregunta4.getText();
                                            respuesta1 = campoRespuesta1.getText();
                                            respuesta2 = campoRespuesta2.getText();
                                            respuesta3 = campoRespuesta3.getText();
                                            respuesta4 = campoRespuesta4.getText();
                if (!pregunta1.isEmpty() & !pregunta2.isEmpty() & !pregunta3.isEmpty() & !pregunta4.isEmpty() & 
                        !respuesta1.isEmpty() & !respuesta2.isEmpty() & !respuesta3.isEmpty() & !respuesta4.isEmpty()) {
                        botonGuardar.setEnabled(true);
                } else{
                        botonGuardar.setEnabled(false);
                        JOptionPane.showMessageDialog(rootPane, 
                                            "Debe rellenar todos los campos", "Mensaje", JOptionPane.ERROR_MESSAGE);
                }
    }//GEN-LAST:event_botonGuardarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonModDU;
    private javax.swing.JButton botonVcontraseñas;
    private javax.swing.JPasswordField campoContra;
    private javax.swing.JPasswordField campoContra2;
    private javax.swing.JTextField campoPregunta1;
    private javax.swing.JTextField campoPregunta2;
    private javax.swing.JTextField campoPregunta3;
    private javax.swing.JTextField campoPregunta4;
    private javax.swing.JTextField campoRespuesta1;
    private javax.swing.JTextField campoRespuesta2;
    private javax.swing.JTextField campoRespuesta3;
    private javax.swing.JTextField campoRespuesta4;
    private javax.swing.JTextField campoUsuario;
    private javax.swing.JLabel etiquetaContra;
    private javax.swing.JLabel etiquetaContra2;
    private javax.swing.JLabel etiquetaPregunta1;
    private javax.swing.JLabel etiquetaUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel2;
    // End of variables declaration//GEN-END:variables
}
